### ISSUE TITLE
Yuzuki Rosetta can increase ddr3 to 512mb

### ISSUE THREAD

**Issue by lamthientieu** [YuzukiHD/YuzukiRosetta#1]
Can I change to increase ddr3 capacity to 512mb or 1g?
And can I ask if the MEMS below is a MEMS mic or not
Cortex A7 * 2
DDR3 128MB
XR829 Wi-Fi，BT
MEMS
Audio Codecs & 3.5mm

**Comment by YuzukiTsuru** [comment]
no，DRAM is sip in R328 chip package，besides Dual A7 It is not possible to use 512M of memory under normal circumstances
